import { db } from "../../../db";
import {
  Expense,
  CreateExpenseDto,
  CreateExpenseDetailDto,
} from "../../../../shared/interfaces/expense.interface";

export class ExpenseRepository {
  getPeriod(year: number, month: number) {
    const start = `${year}-${String(month).padStart(2, "0")}-01`;

    const end =
      month === 12
        ? `${year + 1}-01-01`
        : `${year}-${String(month + 1).padStart(2, "0")}-01`;

    return { start, end };
  }

  findAllByPeriod(year: number, month: number) {
    const { start, end } = this.getPeriod(year, month);

    return db
      .prepare(
        `
      SELECT *
      FROM v_expenses_summary
      WHERE expense_date >= ?
        AND expense_date < ?
      ORDER BY expense_date DESC
    `,
      )
      .all(start, end) as Expense[];
  }

  findOne(expense_id: number) {
    const expense = db
      .prepare(`SELECT * FROM v_expenses_summary WHERE id = ?`)
      .get(expense_id);

    if (expense) {
      const details = db
        .prepare(
          `SELECT * FROM expense_details WHERE expense_id = ? AND is_active = 1`,
        )
        .all(expense_id);

      return {
        ...expense,
        detail: details,
      };
    }
  }

  create(dto: CreateExpenseDto) {
    const insertExpenseStmt = db.prepare(
      `INSERT INTO expenses (
        description,
        expense_date
      ) VALUES (@description, @expense_date)
      `,
    );

    const insertDetailStmt = db.prepare(
      `INSERT INTO expense_details (
        description,
        value,
        category_id,
        expense_id,
        is_auto_generated,
         is_active
      ) VALUES (@description, @value, @category_id, @expense_id, @is_auto_generated,  @is_active)
      `,
    );

    const executeTransaction = db.transaction((data: CreateExpenseDto) => {
      // 1. Insertar la cabecera
      const expenseResult = insertExpenseStmt.run({
        description: data.description,
        expense_date: data.expense_date,
      });

      const expenseId = Number(expenseResult.lastInsertRowid);

      // 2. Insertar el detalle automático asociado
      insertDetailStmt.run({
        description: data.description,
        value: data.value,
        category_id: data.category_id ?? null,
        expense_id: expenseId,
        is_auto_generated: 1, // Flag de carga rápida/automática
        is_active: 1,
      });

      return expenseId;
    });

    const createdExpenseId = executeTransaction(dto);

    return { id: createdExpenseId, ...dto };
  }

  createDetail(dto: CreateExpenseDetailDto) {
    const createDetailStmt = db.prepare(
      `INSERT INTO expense_details (
        description, 
        value, 
        expense_id, 
        category_id,
        is_auto_generated,
        is_active
      ) VALUES (
        @description, 
        @value, 
        @expense_id, 
        @category_id,
        @is_auto_generated,
        @is_active
      )`,
    );

    const deleteAutoGeneratedDetailStmt = db.prepare(
      "UPDATE expense_details SET is_active = 0 WHERE expense_id = @expense_id AND is_auto_generated = true",
    );

    const executeTransaction = db.transaction(
      (data: CreateExpenseDetailDto) => {
        createDetailStmt.run({
          description: data.description,
          category_id: data.category_id,
          value: data.value,
          expense_id: data.expense_id,
          is_auto_generated: 0,
          is_active: 1,
        });

        deleteAutoGeneratedDetailStmt.run({
          expense_id: data.expense_id,
        });
      },
    );

    const createdExpenseDetailId = executeTransaction(dto);
    return { createdExpenseDetailId, dto };
  }

  deleteExpense(id: number) {
    const stmt = db.prepare(`DELETE FROM expenses WHERE id = ?`);
    return stmt.run(id);
  }

  deleteDetail(detail_id: number) {
    const stmt = db.prepare("DELETE FROM expense_details WHERE id = ?");
    return stmt.run(detail_id);
  }

  getSummaryByCategories(year: number, month: number) {
    const { start, end } = this.getPeriod(year, month);

    const stmt = db.prepare(`
      SELECT 
        COALESCE(c.category, 'SIN CATEGORIA') AS name,
        SUM(ed.value) AS value
      FROM expense_details ed
      INNER JOIN expenses e ON e.id = ed.expense_id 
      LEFT JOIN categories c 
        ON ed.category_id = c.id
      WHERE ed.is_active = true AND e.expense_date >= ? AND e.expense_date < ?
      GROUP BY c.id, c.category;
    `);

    return stmt.all(start, end);
  }
}
